apiVersion: batch/v1
kind: Job
metadata:
  name: 090-humio-license-secret
  annotations:
    argocd.argoproj.io/sync-wave: "090"
  namespace: humio-logging
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |

              oc create secret generic humio-license -n humio-logging --from-literal=data={{.Values.humioLicense}}

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4