apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  zen:
    ignoreReady: false
    instanceId: iaf-zen-cpdservice
    serviceInstanceName: iaf-zen-cpdservice
    serviceNamespace: {{.Values.spec.eventManager.namespace}}
    storage:
      storageClassName: {{.Values.spec.storageClass}}
  ldap:
    port: '389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '636'
    url: 'ldap://localhost:389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: {{.Values.spec.storageClass}}
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    iafCartridgeRequirementsName: ''
    netDisco: false
    observers:
      docker: false
      taddm: false
      servicenow: true
      ibmcloud: false
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: true
      rest: true
      appdynamics: false
      jenkins: false
      zabbix: false
      file: true
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    storageClassElasticTopology: {{.Values.spec.storageClass}}
    storageClassFileObserver: {{.Values.spec.storageClass}}
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
  version: {{.Values.spec.eventManager.version}}
  entitlementSecret: ibm-entitlement-key
  clusterDomain: ''
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: {{.Values.spec.storageClass}}
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: {{.Values.spec.storageClass}}
    storageClassKafka: {{.Values.spec.storageClass}}
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: {{.Values.spec.storageClass}}
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: {{.Values.spec.storageClass}}
    storageClassCouchdb: {{.Values.spec.storageClass}}
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: {{.Values.spec.storageClass}}
    storageSizeCassandraData: 50Gi
    storageClassElastic: {{.Values.spec.storageClass}}
    storageClassImpactGUI: {{.Values.spec.storageClass}}
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: {{.Values.spec.storageClass}}
  deploymentType: {{.Values.spec.eventManager.deploymentType}}
