core:
  ibm-aiops:
    install: false
    pullToken: <PULL_TOKEN>
solutions:
  TurbonomicInstall: false
  HumioInstall: false
  HumioLicense: <HUMIO_LICENSE>
  AWXInstall: false
  IstioInstall: false
  ELKInstall: false
activeBranch: main