{{- if .Values.solutions.AWXInstall }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: awx
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/2_addons/awx
    repoURL: 'https://github.com/niklaushirt/cp4waiops-demo-gitops'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      #- Validate=false
      - SkipDryRunOnMissingResource=true
      - FailOnSharedResource=true
      - CreateNamespace=true
{{- end }}