apiVersion: batch/v1
kind: Job
metadata:
  name: 220-argo-cp4waiops-cleanup-stuck-pods
  annotations:
    argocd.argoproj.io/sync-wave: "220"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -x

              oc delete pods $(oc get pod -n {{.Values.spec.aiManager.namespace}} --no-headers| grep -v "1/1\|2/2\|3/3\|4/4"| grep -v "Completed"|awk '{print$1}') -n {{.Values.spec.aiManager.namespace}} || true

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4
