apiVersion: batch/v1
kind: Job
metadata:
  name: 999-get-logins-ldap
  annotations:
    argocd.argoproj.io/sync-wave: "999"
    argocd.argoproj.io/hook: PostSync
  namespace: {{.Values.aiManagerNamespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 LDAP "
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    " 
              echo "            📥 OPENLDAP:"
              echo "    " 
              echo "                🌏 URL:      http://$(oc get route -n default openldap-admin -o jsonpath={.spec.host})"
              echo "                🧑 User:     cn=admin,dc=ibm,dc=com"
              echo "                🔐 Password: P4ssw0rd!"
              echo "    "
              echo "    "
              echo "    "
              echo "    "
          
      serviceAccountName: openshift-argocd-admin-ai
      restartPolicy: Never
  backoffLimit: 4
