{{- if .Values.ibmaiops.install }}

apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-aiops-install-aiops
  namespace: ibm-aiops-installer
spec:
  serviceAccountname: ibm-aiops-installer-admin
  template:
    metadata:
      labels:
        app: ibm-aiops-installer
    spec:
      containers:
        - name: install
          image: quay.io/niklaushirt/ibm-aiops-tools:2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "2024Mi"
              cpu: "1200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              #set -x

          env:
          - name: INSTALL_REPO
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration
                key: INSTALL_REPO
          - name: ENTITLED_REGISTRY_KEY
            valueFrom:
              configMapKeyRef:
                name: ibm-aiops-install-configuration
                key: ENTITLED_REGISTRY_KEY
          volumeMounts:
            - name: config-file
              mountPath: /tmp/config-file
      volumes:
        - name: config-file
          configMap:
            name: ibm-aiops-install-configuration
            items:
            - key: INSTALLATION_CONFIG.yaml
              path: INSTALLATION_CONFIG.yaml
      restartPolicy: Never
  backoffLimit: 400

{{- end }}