apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-argocd-admin-ai
  namespace: turbonomic
  annotations:
    argocd.argoproj.io/sync-wave: "9"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-argocd-admin-ai-turbonomic
  annotations:
    argocd.argoproj.io/sync-wave: "10"
subjects:
  - kind: ServiceAccount
    name: openshift-argocd-admin-ai
    namespace: turbonomic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

