kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: t8c-operator
  annotations:
    argocd.argoproj.io/sync-wave: "20"
subjects:
- kind: ServiceAccount
  name: t8c-operator
roleRef:
  kind: Role
  name: t8c-operator
  apiGroup: rbac.authorization.k8s.io
