apiVersion: batch/v1
kind: Job
metadata:
  name: 999-get-logins-turbonomic
  annotations:
    argocd.argoproj.io/sync-wave: "999"
    argocd.argoproj.io/hook: PostSync
  namespace: turbonomic
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    🚀 Turbonomic Dashboard "
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    -----------------------------------------------------------------------------------------------------------------------------------------------"
              echo "    "
              echo "            📥 Turbonomic Dashboard :"
              echo ""
              echo "                🌏 URL:      https://$(oc get route -n turbonomic api -o jsonpath={.spec.host})"
              echo "                🧑 User:     administrator"
              echo "                🔐 Password: As set at init step"
              echo "    "
              echo "    "
              echo "    "
              echo "    "

          
      serviceAccountName: openshift-argocd-admin-ai
      restartPolicy: Never
  backoffLimit: 4
