apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-topology-service-account
  namespace: {{.Values.spec.aiManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "110"
  labels:
    managedByUser: 'true'
imagePullSecrets:
  - name: ibm-entitlement-key