apiVersion: batch/v1
kind: Job
metadata:
  name: 120-argo-cp4waiops-wait-csv
  annotations:
    argocd.argoproj.io/sync-wave: "120"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |

              #sleep 240



              while : ; do
                READY=$(oc get csv  -n {{.Values.spec.aiManager.namespace}})
                if [[ $READY  =~ 'Installing' ]]; then
                  echo '"AIOps Operator" is not ready yet.'
                  sleep 10s
                else
                  break
                fi
              done


      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4
