apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging 
  annotations:
    argocd.argoproj.io/sync-wave: "110"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  targetNamespaces:
  - openshift-logging 
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging 
  annotations:
    argocd.argoproj.io/sync-wave: "110"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  channel: "stable-5.3"
  name: cluster-logging
  source: redhat-operators 
  sourceNamespace: openshift-marketplace