apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-argocd-admin-ai
  namespace: robot-shop
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-argocd-admin-ai-robot-shop
  annotations:
    argocd.argoproj.io/sync-wave: "10"
subjects:
  - kind: ServiceAccount
    name: openshift-argocd-admin-ai
    namespace: robot-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
