{{- if .Values.ibm-aiops.install }}
apiVersion: v1                     
kind: Namespace
metadata:
  name: {{.Values.ibm-aiops.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
