{{- if .Values.ibmaiops.install }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: ibm-aiops-install-configuration
  namespace: ibm-aiops-installer
  annotations:
    argocd.argoproj.io/sync-wave: "100"
immutable: false
data:
  # Get your key from here https://myibm.ibm.com/products-services/containerlibrary
  ENTITLED_REGISTRY_KEY: >-
    TEST
  INSTALLATION_CONFIG.yaml: >+
    #*************************************************************************************************************************************************
    #--------------------------------------------------------------------------------------------------------------------------------------
    # Global Configuration
    #--------------------------------------------------------------------------------------------------------------------------------------
    #*************************************************************************************************************************************************

    global_config:
      # Available Names: Arya,Bear,Cersei,Cersei1,Daenerys,Groot,Hodor,Hofstadter,Howard,Jimmy,John,King,Lemmy,Nightking,Penny,Raj,Robot1,Robot2,Robot3,Robot4,Robot5,Sansa,Sheldon,Sherlock,Slash,Tormund,Tyrion,Walker,Watson
      environment_name: Lemmy
      cloud_platform: existing-ocp

      # --------------------------------------------------------------------------------------------------------------------------------------
      # Pull Registires
      # --------------------------------------------------------------------------------------------------------------------------------------
      entitled_registry: {{.Values.ibmaiops.entitled_registry}}
      entitled_registry_user: {{.Values.ibmaiops.entitled_registry_user}}
      catalog_image: {{.Values.ibmaiops.catalog_image}}
      # entitled_registry: cp.icr.io
      # entitled_registry_user: cp
      # catalog_image: icr.io/cpopen/ibm-operator-catalog:latest

      # --------------------------------------------------------------------------------------------------------------------------------------
      # Notifications and Cards
      # --------------------------------------------------------------------------------------------------------------------------------------
      # Create Welcome Cards in ibm-aiops
      create_cards: {{.Values.ibmaiops.create_cards}}
      # Create App Menu Items in OCP
      create_ocp_items: {{.Values.ibmaiops.create_ocp_items}}
      # Create Notifications in OCP
      create_ocp_notifications: {{.Values.ibmaiops.create_ocp_notifications}}
      position_ocp_notifications: BannerBottom
      position_final_ocp_notification: BannerTop


      # --------------------------------------------------------------------------------------------------------------------------------------
      # Passwords and Licenses
      # --------------------------------------------------------------------------------------------------------------------------------------
      # Use this Password for all Instances
      global_password: {{.Values.ibmaiops.global_password}}
      # Set this value to True to accept all licenses
      accept_all_licenses: {{.Values.ibmaiops.accept_all_licenses}}
      license_token: {{.Values.ibmaiops.license_token}}


    # *************************************************************************************************************************************************
    # -------------------------------------------------------------------------------------------------------------------------------------
    # OpenShift Configuration
    # --------------------------------------------------------------------------------------------------------------------------------------
    # *************************************************************************************************************************************************

    openshift:

    - name: "mycluster"
      ocp_version: "4.12"
      cluster_name: "mycluster"
      domain_name: example.com
      openshift_storage:
      - storage_name: auto-storage
        storage_type: auto
        # Alternatively use
        #storage_name: ibm-roks-storage
        #storage_type: custom
        #ocp_storage_class_file: ibmc-file-gold-gid
        #ocp_storage_class_block: ibmc-block-gold




    #*************************************************************************************************************************************************
    #--------------------------------------------------------------------------------------------------------------------------------------
    # IBM AIOPS Configuration
    #--------------------------------------------------------------------------------------------------------------------------------------
    #*************************************************************************************************************************************************

    ibmaiops:


    #--------------------------------------------------------------------------------------------------------------------------------------

    # CloudPak for AIOps Base Install

    #--------------------------------------------------------------------------------------------------------------------------------------

    - project: ibm-aiops
      instances:
      - name: {{.Values.ibmaiops.namespace}}
        kind: IBMAIOps
        install: true

        # --------------------------------------------------------------------------------------------------------------------------------------
        # Install Sizing
        # current_ibm-aiops_feature
        # ibm-aiops Size of the install (small: PoC/Demo, tall: Production)
        aiops_size: {{.Values.ibmaiops.install_repo}}
        # Custom Sizing File (aiops_size must be set to "custom")
        #custom_size_file: none

        # --------------------------------------------------------------------------------------------------------------------------------------
        # Install Details
        # Name of the ibm-aiops instance
        aiops_name: {{.Values.ibmaiops.aiops_name}}
        # Version of the catalog subscription
        subscription_channel: {{.Values.ibmaiops.subscription_channel}}
        # Freeze the version of the Catalog image by patching CatalogSource
        freeze_catalog: {{.Values.ibmaiops.freeze_catalog}}
        # Install Feature Flags
        install_feature_flags: {{.Values.ibmaiops.install_feature_flags}}


        # --------------------------------------------------------------------------------------------------------------------------------------
        # Storage Classes Override for this Instance
        #storage_class_file: automatic
        #storage_class_block: automatic

        # --------------------------------------------------------------------------------------------------------------------------------------
        # Install with CASE Files
        # --------------------------------------------------------------------------------------------------------------------------------------
        case_install: false
        case_github_url: "https://github.com/IBM/cloud-pak/raw/master/repo/case"
        case_name: ibm-cp-waiops
        case_version: 1.6.1
        case_inventory_setup: cpaiopsSetup



  INSTALL_REPO: '{{.Values.ibmaiops.install_repo}}'


{{- end }}